### MOVIES GET

GET http://localhost:8080/movies

### MOVIES GET BY ID

GET localhost:8080/movies/1

### MOVIES ADD

POST http://localhost:8080/movies
Content-Type: application/json

  {
    "title": "Inception",
    "rating": 10,
    "director": "Christopher Nolan",
    "releaseYear": 2010,
    "genre": "Science Fiction",
    "version": 1
  }

### MOVIES UPDATE BY PUT

PUT http://localhost:8080/movies/1
Content-Type: application/json

{
  "title": "Harry Potter and the philosopher's stone",
  "rating": 7
}

### MOVIES UPDATE BY PATCH

PATCH http://localhost:8080/movies/1
Content-Type: application/json

{
  "rating": 3
}

### MOVIE DELETE

DELETE localhost:8080/movies/1