### MOVIES GET

GET http://localhost:8080/movies
Authorization: Bearer {{auth-token}}

### MOVIES GET BY ID

GET localhost:8080/movies/{{id}}
Authorization: Bearer {{auth-token}}

### MOVIES ADD

POST http://localhost:8080/movies
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "title": "Inception",
  "rating": 10,
  "director": "Christopher Nolan",
  "releaseYear": 2010,
  "genre": "Science Fiction",
  "version": 1
}

### MOVIES UPDATE BY PUT

PUT http://localhost:8080/movies/{{id}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "title": "Harry Potter and the philosopher's stone",
  "rating": 7
}

### MOVIES UPDATE BY PATCH

PATCH http://localhost:8080/movies/{{id}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
  "rating": 3
}

### MOVIE DELETE

DELETE localhost:8080/movies/{{id}}
Authorization: Bearer {{auth-token}}

### AUTH

### Login as a user

POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "user@mail.com",
  "password": "usersecret"
}

> {% client.global.set("auth-token", response.body.token); %}

### Login as an admin

POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin@mail.com",
  "password": "adminsecret"
}

> {% client.global.set("auth-token", response.body.token); %}
