### MOVIES GET

GET http://localhost:8080/movies

### MOVIES GET BY ID

GET localhost:8080/movies/{{id}}

### MOVIES ADD

POST http://localhost:8080/movies
Content-Type: application/json

[
  {
    "id": "124e4567-e89b-12d6-a456-426614124000",
    "title": "Titanic",
    "rating": 9,
    "director": "Christopher Nolan",
    "releaseYear": 1993,
    "genre": "Science Fiction"
  }
]

### MOVIES UPDATE BY PUT

PUT http://localhost:8080/movies/{{id}}
Content-Type: application/json

{
  "title": "Harry Potter and the philosopher's stone",
  "rating": 7
}

### MOVIES UPDATE BY PATCH

PATCH http://localhost:8080/movies/124e4567-e89b-12d6-a456-426614124000
Content-Type: application/json

{
  "rating": 3
}

### MOVIE DELETE

DELETE localhost:8080/movies/124e4567-e89b-12d6-a456-426614124000